//file:noinspection GroovyAssignabilityCheck
plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

gradlePlugin {
    plugins {
        publishPlugin {
            id = 'publish-plugin'
            implementationClass = 'dev.sorokin.gradle.publishplugin.GradlePublishPlugin'
        }
    }
}