//file:noinspection GroovyAssignabilityCheck
plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

gradlePlugin {
    plugins {
        publishPlugin {
            id = 'publish-plugin'
            implementationClass = 'dev.sorokin.gradle.publishplugin.GradlePublishPlugin'
        }
    }
}

dependencies {
    compileOnly 'org.jetbrains:annotations:24.1.0'

    testImplementation platform('org.junit:junit-bom:5.11.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core:3.26.3'
    testImplementation gradleTestKit()

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}